name: Myfirstactions
on: 
  push:
    branches:
      - 'vp-rem'  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4   
     - name: Myfirst-stage
       run: | 
          pwd
          ls -la  











    #  - name: Fetch Source code
    #    uses: actions/checkout@v4
    #  - name: Build artifacts
    #    run: | 
    #       mvn install
    #       mv target/vprofile-v2.war .
    #       rm -rf target
    #       mkdir target
    #       mv vprofile-v2.war target/
    #       ls -l target/
